const data = {
    products: [
        {
            _id: '1',
            category: 'Shirts',
            name: 'Nike Slim Shirt',
            image: './images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'Slim fit. The model (height 6) is wearing a size 40',
        },
        {
            _id: '2',
            category: 'Shirts',
            name: 'Adidas Slim Shirt',
            image: './images/p2.jpg',
            price: 100,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'Slim fit. The model (height 6) is wearing a size 40',
        },
        {
            _id: '3',
            category: 'Shirts',
            name: 'Lacoste Slim Shirt',
            image: './images/p3.jpg',
            price: 200,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'Slim fit. The model (height 6) is wearing a size 40',
        },
        {
            _id: '4',
            category: 'Pants',
            name: 'Nike Slim Pant',
            image: './images/p4.jpg',
            price: 85,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 13,
            description: 'Slim fit. The model (height 6) is wearing a size 42',
        },
        {
            _id: '5',
            category: 'Pants',
            name: 'Puma Slim Pant',
            image: './images/p5.jpg',
            price: 90,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 11,
            description: 'Slim fit. The model (height 6) is wearing a size 40',
        },
        {
            _id: '6',
            category: 'Pants',
            name: 'Adidas Fit Pant',
            image: './images/p6.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.9,
            numReviews: 21,
            description: 'Regular fit. The model (height 6) is wearing a size 40',
        },
    ]
};

export default data;